name: cook-inlet-catalogs
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - cartopy
  - cf_pandas
  - jupyter
  - matplotlib-base
  - pip
  - pandas
  - pip:
    - git+https://github.com/intake/intake.git
    - git+https://github.com/axiom-data-science/cook-inlet-catalogs.git
